// reqloom.d.ts
//
// TypeScript declarations for the Reqloom hook sandbox `ctx` object.
// This file is GENERATED by `reqloom`; do not edit by hand —
// regenerate via `reqloom lint --emit-typings`.
//
// The hook sandbox is QuickJS, not full Node. Globals not listed here
// are not available; in particular there is no `require`, no `fetch`,
// no filesystem, no timers.

declare namespace Reqloom {
    type HttpMethod =
        | "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";

    interface MutableRequest {
        method: HttpMethod;
        url: string;
        headers: Record<string, string>;
        body?: string;
    }

    interface ResponseView {
        readonly status: number;
        readonly headers: Readonly<Record<string, string>>;
        readonly body: string;
    }

    interface Base64Codec {
        encode(value: string): string;
        decode(value: string): string;
    }

    interface HexCodec {
        encode(value: string): string;
        decode(value: string): string;
    }

    /// RFC 3986 URL-component codec (unreserved chars pass through).
    interface UrlCodec {
        encode(value: string): string;
        decode(value: string): string;
    }

    /// HMAC families. Keys and data are strings; output is the raw MAC.
    /// Wrap with `ctx.hex.encode` / `ctx.base64.encode` for transport.
    interface HmacApi {
        sha1(key: string, data: string): string;
        sha256(key: string, data: string): string;
        sha512(key: string, data: string): string;
    }

    interface HashApi {
        sha256(data: string): string;
    }

    /// JWT signing. HS256/HS512 only (RS256 plumbing deferred).
    interface JwtApi {
        sign(payloadJson: string, key: string,
             alg: "HS256" | "HS512"): string;
    }

    interface JsonApi {
        stringify(value: unknown): string;
        parse(text: string): unknown;
    }

    type EnvView = Readonly<Record<string, string>>;

    /// Values come from the OS keychain. Must NOT be logged or sent to
    /// non-target hosts.
    type SecretView = Readonly<Record<string, string>>;

    interface Context {
        request: MutableRequest;
        readonly response?: ResponseView;
        readonly env: EnvView;
        readonly secret: SecretView;

        readonly base64: Base64Codec;
        readonly hex:    HexCodec;
        readonly url:    UrlCodec;
        readonly hmac:   HmacApi;
        readonly hash:   HashApi;
        readonly jwt:    JwtApi;
        readonly json:   JsonApi;
    }
}

declare type PreRequestHook =
    (ctx: Reqloom.Context) => void;

declare type PostResponseHook =
    (ctx: Reqloom.Context) => void;
