// StaticHookTypingsEmitter — see header. The emitted body matches the hook
// `ctx` surface (codecs + crypto helpers). When the QuickJS bridge exposes
// these helpers, the binding code reads THIS file's shape — the typings
// stay the source of truth for what hook authors can rely on.
#include "StaticHookTypingsEmitter.h"

#include <fstream>
#include <string>
#include <string_view>
#include <system_error>
#include <utility>

namespace fs = std::filesystem;

namespace reqloom::engine {

namespace {

// The full body of `reqloom.d.ts`. Kept as a single literal so the
// emitter is trivially auditable — what you read here is exactly what
// hook authors see in their editor.
constexpr std::string_view kTypingsBody = R"TS(// reqloom.d.ts
//
// TypeScript declarations for the Reqloom hook sandbox `ctx` object.
// This file is GENERATED by `reqloom`; do not edit by hand —
// regenerate via `reqloom lint --emit-typings`.
//
// The hook sandbox is QuickJS, not full Node. Globals not listed here
// are not available; in particular there is no `require`, no `fetch`,
// no filesystem, no timers.

declare namespace Reqloom {
    type HttpMethod =
        | "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";

    interface MutableRequest {
        method: HttpMethod;
        url: string;
        headers: Record<string, string>;
        body?: string;
    }

    interface ResponseView {
        readonly status: number;
        readonly headers: Readonly<Record<string, string>>;
        readonly body: string;
    }

    interface Base64Codec {
        encode(value: string): string;
        decode(value: string): string;
    }

    interface HexCodec {
        encode(value: string): string;
        decode(value: string): string;
    }

    /// RFC 3986 URL-component codec (unreserved chars pass through).
    interface UrlCodec {
        encode(value: string): string;
        decode(value: string): string;
    }

    /// HMAC families. Keys and data are strings; output is the raw MAC.
    /// Wrap with `ctx.hex.encode` / `ctx.base64.encode` for transport.
    interface HmacApi {
        sha1(key: string, data: string): string;
        sha256(key: string, data: string): string;
        sha512(key: string, data: string): string;
    }

    interface HashApi {
        sha256(data: string): string;
    }

    /// JWT signing. HS256/HS512 only (RS256 plumbing deferred).
    interface JwtApi {
        sign(payloadJson: string, key: string,
             alg: "HS256" | "HS512"): string;
    }

    interface JsonApi {
        stringify(value: unknown): string;
        parse(text: string): unknown;
    }

    type EnvView = Readonly<Record<string, string>>;

    /// Values come from the OS keychain. Must NOT be logged or sent to
    /// non-target hosts.
    type SecretView = Readonly<Record<string, string>>;

    interface Context {
        request: MutableRequest;
        readonly response?: ResponseView;
        readonly env: EnvView;
        readonly secret: SecretView;

        readonly base64: Base64Codec;
        readonly hex:    HexCodec;
        readonly url:    UrlCodec;
        readonly hmac:   HmacApi;
        readonly hash:   HashApi;
        readonly jwt:    JwtApi;
        readonly json:   JsonApi;
    }
}

declare type PreRequestHook =
    (ctx: Reqloom.Context) => void;

declare type PostResponseHook =
    (ctx: Reqloom.Context) => void;
)TS";

std::expected<void, ReqloomError> writeAtomic(const fs::path& target, std::string_view content) {
    std::error_code ec;
    fs::create_directories(target.parent_path(), ec);
    if (ec) {
        return std::unexpected(ReqloomError{
            ErrorCode::SchemaInvalid,
            ErrorClass::Schema,
            "typings: cannot create dir " + target.parent_path().string() + ": " + ec.message()});
    }

    auto temp = target;
    temp += ".tmp";
    {
        std::ofstream out{temp, std::ios::binary | std::ios::trunc};
        if (!out) {
            return std::unexpected(
                ReqloomError{ErrorCode::SchemaInvalid,
                              ErrorClass::Schema,
                              "typings: cannot open temp file " + temp.string()});
        }
        out << content;
        if (!out) {
            return std::unexpected(
                ReqloomError{ErrorCode::SchemaInvalid,
                              ErrorClass::Schema,
                              "typings: failed writing temp file " + temp.string()});
        }
    }

    // On POSIX, rename(2) atomically replaces the target. On Windows,
    // std::filesystem::rename fails when the target exists — remove it
    // first. The small race (crash between remove and rename leaves the
    // file gone) is acceptable for a generated typings file.
#ifdef _WIN32
    std::error_code removeEc;
    fs::remove(target, removeEc);
#endif
    fs::rename(temp, target, ec);
    if (ec) {
        std::error_code _;
        fs::remove(temp, _);
        return std::unexpected(ReqloomError{ErrorCode::SchemaInvalid,
                                             ErrorClass::Schema,
                                             "typings: cannot rename " + temp.string() + " → " +
                                                 target.string() + ": " + ec.message()});
    }
    return {};
}

}  // namespace

StaticHookTypingsEmitter::StaticHookTypingsEmitter() = default;
StaticHookTypingsEmitter::~StaticHookTypingsEmitter() = default;

TypingsEmitResult StaticHookTypingsEmitter::emit(const fs::path& targetDir,
                                                 const Project& /*project*/,
                                                 bool overwrite) {
    auto target = targetDir / "reqloom.d.ts";

    std::error_code ec;
    if (fs::exists(target, ec) && !overwrite) {
        return std::unexpected(ReqloomError{ErrorCode::SchemaInvalid,
                                             ErrorClass::Schema,
                                             "typings: reqloom.d.ts exists in " +
                                                 targetDir.string() +
                                                 " (pass overwrite=true to replace)"});
    }

    fs::create_directories(targetDir, ec);
    if (ec) {
        return std::unexpected(
            ReqloomError{ErrorCode::SchemaInvalid,
                          ErrorClass::Schema,
                          "typings: cannot create " + targetDir.string() + ": " + ec.message()});
    }

    if (auto r = writeAtomic(target, kTypingsBody); !r) {
        return std::unexpected(r.error());
    }
    return target;
}

}  // namespace reqloom::engine
